### PR TITLE
Fix unhandled ResultSet.json errors, prepare 1.6.0

### LINKED ISSUE #309: Uncatchable parse errors when incoming data is not a valid JSON
Wrapping the `client.query` method does not catch this error. This error is caught with `unhandledRejection` listener on process.

Here is the exception
```
Node.js v22.3.0
undefined:1
024-09-09 19:30:37.979","level":"info","event_type":"getStats"}
 ^

SyntaxError: Unexpected number in JSON at position 1 (line 1 column 2)
    at JSON.parse (<anonymous>)
    at Object.json (/usr/src/app/node_modules/.pnpm/@clickhouse+client@1.5.0/node_modules/@clickhouse/client/dist/result_set.js:134:41)
    at Transform.<anonymous> (/usr/src/app/node_modules/.pnpm/@clickhouse+client@1.5.0/node_modules/@clickhouse/client/dist/result_set.js:88:41)
    at Transform.emit (node:events:520:28)
    at Transform.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)
    at Readable.push (node:internal/streams/readable:391:5)
    at Transform.transform [as _transform] (/usr/src/app/node_modules/.pnpm/@clickhouse+client@1.5.0/node_modules/@clickhouse/client/dist/result_set.js:154:34)
    at Transform._write (node:internal/streams/transform:171:8)
```

### PR DESCRIPTION
**Pull request by slvrtrn**
## Summary

Resolves #309 

## Checklist
- [x] Unit and integration tests covering the common scenarios were added
- [x] A human-readable description of the changes was provided to include in CHANGELOG

### CODE REVIEW

File: packages/client-node/src/result_set.ts [hunk 1]
```diff
@@ -82,16 +82,12 @@ export class ResultSet<Format extends DataFormat | unknown>
...
       const result: T[] = []
-      await new Promise((resolve, reject) => {
-        const stream = this.stream<T>()
-        stream.on('data', (rows: Row[]) => {
-          for (const row of rows) {
-            result.push(row.json())
-          }
-        })
-        stream.on('end', resolve)
-        stream.on('error', reject)
```
Comment (mshustov) [inline packages/client-node/src/result_set.ts:93]: not needed?

Comment (slvrtrn) [reply packages/client-node/src/result_set.ts:93]: This is the exact part that produced unhandled exceptions.

```ts
for await (const rows of stream) {
  for (const row of rows) {
    result.push(row.json())
  }
}
```
achieves the same on the modern Node.js versions, but we can catch the error properly on the app side.

**Review by mshustov — APPROVED** [review]
